"""SQLModel table definitions."""

import json
from datetime import datetime, timezone

from sqlmodel import Field, SQLModel

# ---------------------------------------------------------------------------
# Status constants — imported by repo.py for validation
# ---------------------------------------------------------------------------

TASK_STATUSES: frozenset[str] = frozenset(
    {"not_started", "in_progress", "complete", "skipped"}
)
SESSION_STATUSES: frozenset[str] = frozenset({"in_progress", "complete"})
VOCAB_STATUSES: frozenset[str] = frozenset({"new", "learning", "mastered"})

# Default tasks JSON for new TutorSession rows — matches architecture §9 exactly.
_DEFAULT_TASKS: str = json.dumps(
    {
        "listening": {"status": "not_started", "summary": None},
        "writing": {"status": "not_started", "summary": None},
        "speaking": {"status": "not_started", "summary": None},
        "grammar": {"status": "not_started", "summary": None},
        "onboarding": {"status": "not_started", "transcript": []},
    }
)


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------


class LlmCall(SQLModel, table=True):
    """One row per Anthropic API call — the core observability record."""

    id: int | None = Field(default=None, primary_key=True)
    model: str
    agent: str
    session_id: str | None = None
    input_tokens: int
    output_tokens: int
    cost_usd: float
    latency_ms: int
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class User(SQLModel, table=True):
    """A registered user — one row per unique user_id."""

    user_id: str = Field(primary_key=True)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )


class UserProfile(SQLModel, table=True):
    """CEFR profile produced by the Onboarding agent.

    List fields (grammar_gaps, grammar_strengths, interests) are stored as
    JSON strings and deserialised by the repo layer.

    assessment_method values:
      "self_declared_novice"  — A1 defaults set without conversation; may be
                                promoted by the Feedback agent after session 1.
      "conversation_assessed" — profile derived from evaluated onboarding transcript.
    """

    user_id: str = Field(primary_key=True)
    cefr_level: str
    vocabulary_range: str
    grammar_gaps: str  # JSON list
    grammar_strengths: str  # JSON list
    confidence_level: str
    interests: str  # JSON list
    onboarding_transcript: str
    assessment_method: str = Field(default="conversation_assessed")


class TutorSession(SQLModel, table=True):
    """One learning session (Listening → Writing → Speaking → Grammar).

    The tasks column is a JSON string whose shape matches architecture §9.
    turn_count is the DB-backed turn counter (build plan §2.1).
    """

    session_id: str = Field(primary_key=True)
    user_id: str
    topic: str
    date_started: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
    status: str = Field(default="in_progress")
    tasks: str = Field(default=_DEFAULT_TASKS)
    turn_count: int = Field(default=0)


class VocabularyItem(SQLModel, table=True):
    """One vocabulary word or expression tracked for a user.

    topic_tags is a JSON list string; word may be a phrase or collocation.
    """

    id: int | None = Field(default=None, primary_key=True)
    word: str
    user_id: str
    status: str = Field(default="new")
    times_seen: int = Field(default=0)
    times_used_correctly: int = Field(default=0)
    last_seen_session: str | None = None
    topic_tags: str = Field(default="[]")  # JSON list
    # One of: "used_correctly", "not_used", "used_incorrectly"
    usage_signal: str | None = Field(default=None)


class LearningLog(SQLModel, table=True):
    """Per-session learning log generated by the Feedback agent.

    List fields are stored as JSON strings and deserialised by the repo layer.
    """

    log_id: str = Field(primary_key=True)
    user_id: str
    generated_after_session: str | None = None
    date: str  # ISO date string "YYYY-MM-DD"
    status: str = Field(default="active")
    vocabulary_to_review: str = Field(default="[]")  # JSON list
    grammar_focus: str = Field(default="[]")  # JSON list
    grammar_gap_summary: str = Field(default="")
    session_notes: str = Field(default="")
    recommended_topic_tags: str = Field(default="[]")  # JSON list


class EvalResult(SQLModel, table=True):
    """One logged evaluation result (structural, behavioural, or regression)."""

    id: int | None = Field(default=None, primary_key=True)
    agent: str
    input_data: str
    output_data: str
    passed: bool
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
    )
